# Generated by Django 2.1.3 on 2019-03-01 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payitem_number', models.CharField(max_length=100)),
                ('payitem_desc', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('county', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=50)),
                ('awarded_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('letting_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
