# Generated by Django 2.1.3 on 2019-03-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biditem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
