# Generated by Django 2.1.3 on 2019-03-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biditem', '0002_auto_20190303_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='awarded_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
