# Generated by Django 2.1.3 on 2018-12-23 05:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmcircle', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pmcircleinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_code', models.PositiveSmallIntegerField(choices=[(0, 'AASTHO LRFD'), (1, 'ACI 318-14')], default=0)),
                ('section_dia', models.DecimalField(decimal_places=2, default=30, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('clear_cover', models.DecimalField(decimal_places=2, default=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('number_bar', models.PositiveSmallIntegerField(default=6)),
                ('trans_bar_size', models.PositiveSmallIntegerField(choices=[(0, '#3'), (1, '#4'), (2, '#5'), (3, '#6'), (4, '#7'), (5, '#8'), (6, '#9'), (7, '#10'), (8, '#11'), (9, '#14'), (10, '#18')], default=1)),
                ('main_bar_size', models.PositiveSmallIntegerField(choices=[(0, '#3'), (1, '#4'), (2, '#5'), (3, '#6'), (4, '#7'), (5, '#8'), (6, '#9'), (7, '#10'), (8, '#11'), (9, '#14'), (10, '#18')], default=6)),
                ('f_c', models.DecimalField(decimal_places=2, default=4.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('f_y', models.DecimalField(decimal_places=2, default=60, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Es', models.PositiveSmallIntegerField(default=29000)),
                ('transv_type', models.PositiveSmallIntegerField(choices=[(0, 'Spiral'), (1, 'Tied/Other')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pmcloadcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pmcircleinput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmcircle.Pmcircleinput')),
            ],
        ),
        migrations.CreateModel(
            name='Pmcproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
