# Generated by Django 2.1.3 on 2018-12-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmcircle', '0003_pmcircleinput_pmcloadcase_pmcproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcproject',
            name='pmcircleinput',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pmcircle.Pmcircleinput'),
        ),
    ]
