# Generated by Django 2.1.3 on 2018-12-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmcircle', '0004_pmcproject_pmcircleinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmcloadcase',
            name='mu',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pmcloadcase',
            name='pu',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
