# Generated by Django 2.1.3 on 2019-01-20 19:00

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmcircle', '0005_auto_20181228_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pmcproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pmcloadcase',
            name='mu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pmcloadcase',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='pmcproject',
            unique_together={('user', 'project_name')},
        ),
    ]
