# Generated by Django 2.1.3 on 2019-01-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmcircle', '0006_auto_20190120_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmcproject',
            options={'ordering': ['-updated_at']},
        ),
    ]
