district_choices = {
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9
}

county_choices={
            '1' : 'Adams',
            '2' : 'Alexander',
            '3' : 'Bond',
            '4' : 'Boone',
            '5' : 'Brown',
            '6' : 'Bureau',
            '7' : 'Calhoun',
            '8' : 'Carroll',
            '9' : 'Cass',
            '10' : 'Champaign',
            '11' : 'Christian',
            '12' : 'Clark',
            '13' : 'Clay',
            '14' : 'Clinton',
            '15' : 'Coles',
            '16' : 'Cook',
            '17' : 'Crawford',
            '18' : 'Cumberland',
            '19' : 'DeKalb',
            '20' : 'De Witt',
            '21' : 'Douglas',
            '22' : 'DuPage',
            '23' : 'Edgar',
            '24' : 'Edwards',
            '25' : 'Effingham',
            '26' : 'Fayette',
            '27' : 'Ford',
            '28' : 'Franklin',
            '29' : 'Fulton',
            '30' : 'Gallatin',
            '31' : 'Greene',
            '32' : 'Grundy',
            '33' : 'Hamilton',
            '34' : 'Hancock',
            '35' : 'Hardin',
            '36' : 'Henderson',
            '37' : 'Henry',
            '38' : 'Iroquois',
            '39' : 'Jackson',
            '40' : 'Jasper',
            '41' : 'Jefferson',
            '42' : 'Jersey',
            '43' : 'Jo Daviess',
            '44' : 'Johnson',
            '45' : 'Kane',
            '46' : 'Kankakee',
            '47' : 'Kendall',
            '48' : 'Knox',
            '49' : 'LaSalle',
            '50' : 'Lake',
            '51' : 'Lawrence',
            '52' : 'Lee',
            '53' : 'Livingston',
            '54' : 'Logan',
            '55' : 'McDonough',
            '56' : 'McHenry',
            '57' : 'McLean',
            '58' : 'Macon',
            '59' : 'Macoupin',
            '60' : 'Madison',
            '61' : 'Marion',
            '62' : 'Marshall',
            '63' : 'Mason',
            '64' : 'Massac',
            '65' : 'Menard',
            '66' : 'Mercer',
            '67' : 'Monroe',
            '68' : 'Montgomery',
            '69' : 'Morgan',
            '70' : 'Moultrie',
            '71' : 'Ogle',
            '72' : 'Peoria',
            '73' : 'Perry',
            '74' : 'Piatt',
            '75' : 'Pike',
            '76' : 'Pope',
            '77' : 'Pulaski',
            '78' : 'Putnam',
            '79' : 'Randolph',
            '80' : 'Richland',
            '81' : 'Rock Island',
            '82' : 'Saline',
            '83' : 'Sangamon',
            '84' : 'Schuyler',
            '85' : 'Scott',
            '86' : 'Shelby',
            '87' : 'St. Clair',
            '88' : 'Stark',
            '89' : 'Stephenson',
            '90' : 'Tazewell',
            '91' : 'Union',
            '92' : 'Vermilion',
            '93' : 'Wabash',
            '94' : 'Warren',
            '95' : 'Washington',
            '96' : 'Wayne',
            '97' : 'White',
            '98' : 'Whiteside',
            '99' : 'Will',
            '100' : 'Williamson',
            '101' : 'Winnebago',
            '102' : 'Woodford'

}
